name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
      changelog:
        type: string
        description: Changelog
        required: true

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update version
        uses: athombv/github-action-homey-app-version@master
        id: update_version
        with:
          version: ${{ inputs.version }}
          changelog: ${{ inputs.changelog }}

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version ${{ steps.update_version.outputs.version }}
          tagging_message: v${{ steps.update_version.outputs.version }}

      - name: Publish
        uses: athombv/github-action-homey-app-publish@master
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: Summary
        run: echo "Release can be managed at ${{ steps.publish.outputs.url }}" >> $GITHUB_STEP_SUMMARY

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ inputs.changelog }}
          make_latest: true
          tag_name: v${{ steps.update_version.outputs.version }}
