name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
      changelog:
        type: string
        description: Changelog
        required: true

jobs:
  main:
    permissions:
      contents: write
    uses: edwinvdpol/.github/.github/workflows/homey-release.yml@main
    secrets: inherit
